import os
import argparse
import random
import string
import typing
def parse_args():
	parser = argparse.ArgumentParser()
	parser.add_argument('--port', type=int, default=5000)
	parser.add_argument('--debug', action='store_true')
	
	return parser.parse_known_args()[0]
def configure_app(app, config=None):
	# Database config - prefer Postgres
	pg_user = os.environ.get('POSTGRES_USER')
	pg_password = os.environ.get('POSTGRES_PASSWORD')
	pg_host = os.environ.get('POSTGRES_HOST')
	pg_port = os.environ.get('POSTGRES_PORT', '5432')
	pg_db = os.environ.get('POSTGRES_DB')
	if all([pg_user, pg_password, pg_host, pg_db]):
		app.config['SQLALCHEMY_DATABASE_URI'] = f"postgresql://{pg_user}:{pg_password}@{pg_host}:{pg_port}/{pg_db}"
	else:
		app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(os.getcwd(), 'data', 'flowcase.db')
	app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
	
	# Fix for PostgreSQL connection handling in Docker/k8s environments
	# "server closed the connection unexpectedly" and "PGRES_TUPLES_OK" errors
	app.config['SQLALCHEMY_ENGINE_OPTIONS'] = {
		'pool_pre_ping': True,
		'pool_recycle': 300,
		'pool_size': 10,
		'max_overflow': 20
	}
	
	os.makedirs("data", exist_ok=True)
	
	# Load secret key
	if not os.path.exists("data/secret_key"):
		with open("data/secret_key", "w") as f:
			f.write(''.join(random.choice(string.ascii_letters + string.digits) for i in range(64)))
	
	with open("data/secret_key", "r") as f:
		app.secret_key = f.read()
	
	if config:
		app.config.update(config)

	# Ensure cookies work over HTTP for IP access
	app.config['SESSION_COOKIE_SAMESITE'] = 'Lax'
	app.config['SESSION_COOKIE_SECURE'] = False
	app.config['SESSION_COOKIE_PATH'] = '/'

	# OIDC / Authentik config - prefer environment variables
	app.config['AUTHENTIK_ISSUER'] = os.environ.get('AUTHENTIK_ISSUER')
	app.config['AUTHENTIK_CLIENT_ID'] = os.environ.get('AUTHENTIK_CLIENT_ID')
	app.config['AUTHENTIK_CLIENT_SECRET'] = os.environ.get('AUTHENTIK_CLIENT_SECRET')
	# Optional: explicit redirect URI. If not provided, the client will use the URL generated by url_for(..., _external=True)
	app.config['AUTHENTIK_REDIRECT_URI'] = os.environ.get('AUTHENTIK_REDIRECT_URI')
	# Optional: explicit metadata / endpoint URLs. If your provider places discovery under a
	# non-standard path (for example Authentik under /application/o/<app>/), set
	# AUTHENTIK_METADATA_URL to point to the full /.well-known/openid-configuration URL.
	app.config['AUTHENTIK_METADATA_URL'] = os.environ.get('AUTHENTIK_METADATA_URL')
	# Optional explicit endpoints (fallbacks if metadata is not used)
	app.config['AUTHENTIK_AUTHORIZATION_URL'] = os.environ.get('AUTHENTIK_AUTHORIZATION_URL')
	app.config['AUTHENTIK_TOKEN_URL'] = os.environ.get('AUTHENTIK_TOKEN_URL')
	app.config['AUTHENTIK_USERINFO_URL'] = os.environ.get('AUTHENTIK_USERINFO_URL')
		
	return app 
