import os
import argparse
import random
import string
import typing

def parse_args():
	parser = argparse.ArgumentParser()
	parser.add_argument('--port', type=int, default=5000)
	parser.add_argument('--debug', action='store_true')
	
	return parser.parse_known_args()[0]

def configure_app(app, config=None):
	app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(os.getcwd(), 'data', 'flowcase.db')
	app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
	
	os.makedirs("data", exist_ok=True)
	
	# Load secret key
	if not os.path.exists("data/secret_key"):
		with open("data/secret_key", "w") as f:
			f.write(''.join(random.choice(string.ascii_letters + string.digits) for i in range(64)))
	
	with open("data/secret_key", "r") as f:
		app.secret_key = f.read()
	
	if config:
		app.config.update(config)

	# OIDC / Authentik config - prefer environment variables
	app.config['AUTHENTIK_ISSUER'] = os.environ.get('AUTHENTIK_ISSUER')
	app.config['AUTHENTIK_CLIENT_ID'] = os.environ.get('AUTHENTIK_CLIENT_ID')
	app.config['AUTHENTIK_CLIENT_SECRET'] = os.environ.get('AUTHENTIK_CLIENT_SECRET')
	# Optional: explicit redirect URI. If not provided, the client will use the URL generated by url_for(..., _external=True)
	app.config['AUTHENTIK_REDIRECT_URI'] = os.environ.get('AUTHENTIK_REDIRECT_URI')

	# Optional: explicit metadata / endpoint URLs. If your provider places discovery under a
	# non-standard path (for example Authentik under /application/o/<app>/), set
	# AUTHENTIK_METADATA_URL to point to the full /.well-known/openid-configuration URL.
	app.config['AUTHENTIK_METADATA_URL'] = os.environ.get('AUTHENTIK_METADATA_URL')
	# Optional explicit endpoints (fallbacks if metadata is not used)
	app.config['AUTHENTIK_AUTHORIZATION_URL'] = os.environ.get('AUTHENTIK_AUTHORIZATION_URL')
	app.config['AUTHENTIK_TOKEN_URL'] = os.environ.get('AUTHENTIK_TOKEN_URL')
	app.config['AUTHENTIK_USERINFO_URL'] = os.environ.get('AUTHENTIK_USERINFO_URL')
		
	return app 